# Generated by Django 4.2.9 on 2024-02-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Player',
        ),
    ]
