# Generated by Django 4.2.9 on 2024-02-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_record_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='city',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='zipcode',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='address',
            new_name='reg_no',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='state',
            new_name='role',
        ),
    ]
