# Generated by Django 4.2.9 on 2024-02-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_femaleplayer_maleplayer_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleplayer',
            name='role',
            field=models.CharField(default='Setter', max_length=100),
            preserve_default=False,
        ),
    ]
