# Generated by Django 4.2.9 on 2024-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_maleplayer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleplayer',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maleplayer',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
