# Generated by Django 4.2.9 on 2024-03-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_femaleplayer_image_path_maleplayer_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femaleplayer',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='maleplayer',
            name='image_path',
        ),
    ]
